# Generated by Django 3.0.5 on 2025-03-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_auto_20250312_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='class_name',
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(default='لا يوجد وصف'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='grade',
            field=models.CharField(choices=[('one', 'one'), ('two', 'two'), ('three', 'three'), ('four', 'four'), ('five', 'five'), ('six', 'six'), ('seven', 'seven'), ('eight', 'eight'), ('nine', 'nine'), ('ten', 'ten')], default='غير محدد', max_length=10),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
