# Generated by Django 3.0.5 on 2025-03-16 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_lesson_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='grade',
            field=models.CharField(choices=[('one', 'أول متوسط'), ('two', 'ثاني متوسط'), ('three', 'ثالث متوسط'), ('four', 'رابع إعدادي'), ('five', 'خامس إعدادي'), ('six', 'سادس إعدادي')], default='one', max_length=10),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255)),
                ('total_marks', models.PositiveIntegerField()),
                ('obtained_marks', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.StudentExtra')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.TeacherExtra')),
            ],
        ),
    ]
