# Generated by Django 3.0.5 on 2025-03-17 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_auto_20250316_1900'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('lesson', 'exam_name', 'student')},
        ),
    ]
