# Generated by Django 3.0.5 on 2025-03-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_auto_20250317_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notices/'),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='cl',
            field=models.CharField(choices=[('one', 'one'), ('two', 'two'), ('three', 'three'), ('four', 'four'), ('five', 'five'), ('six', 'six')], default='one', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together=set(),
        ),
    ]
