# Generated by Django 3.0.5 on 2025-03-30 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_auto_20250319_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='grade',
            field=models.CharField(choices=[('one', 'First Year Intermediate'), ('two', 'Second Year Intermediate'), ('three', 'Third Year Intermediate'), ('four', 'Fourth Year Secondary'), ('five', 'Fifth Year Secondary'), ('six', 'Sixth Year Secondary')], default='one', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.TeacherExtra', verbose_name='Teacher'),
        ),
    ]
